// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enabled": boolean;
      "autoSync": boolean;
      "showNotifications": boolean;
      "skipUnchanged": boolean;
      "processedFingerprints": string;
      "useCustomCommands": boolean;
      "watchedCollection": string;
      "watchedCollectionKeys": string;
      "syncNotes": boolean;
      "archiveDeletedWithPreview": boolean;
      "debounceSeconds": string;
      "processTimeoutSeconds": string;
      "executionMode": string;
      "wslDistro": string;
      "workspacePath": string;
      "notionToken": string;
      "notionDatabaseId": string;
      "guideLanguage": string;
      "aiTool": string;
      "aiCommand": string;
      "aiArgs": string;
      "aiModel": string;
      "aiEffort": string;
      "autoUpdateCli": boolean;
      "lastUpdateCheck": string;
      "modelOptionsCache": string;
      "configSyncTs": string;
      "aiExtraArgs": string;
      "commandTemplate": string;
      "deleteCommandTemplate": string;
      "promptOverride": string;
      "promptPresets": string;
      "defaultPromptName": string;
    };
  }
}
